### ISSUE TITLE
better keybinds for writing latex

### ISSUE THREAD

**Issue by DronHazra** [wwsalmon/postulate#61]
with the current implementation, a primary issue is that activating latex via `$` plus space feels awkward, especially when you're constantly using variable names like `$x$` or `$n$`. closing blocks is also difficult, with the current method being right arrow + another character. this means that every time i have to reference _any math symbol_ i have to hit `$`, `space`, `n`, `right arrow` and then continue typing. this adds up real fast.

for example, consider typing this paragraph:
```
Lastly we have to prove every other $n$ works. Let $n =
2^a \cdot k$ for odd $k > 1$. We're looking for some  $x$
that satisfies $x\equiv 0\mod 2^{a+1}$ and $x\equiv \pm 1
\mod k$. We know that every residue $\mod n$ occurs in the
numbers $1$ to $2n=2^{a+1}\cdot k$, and thus by the
Chinese Remainder Theorem, every pair of residues $\mod
2^{a+1}$ and $\mod k$ also occurs. Thus $\exists x \equiv
0 \mod 2^{a+1}, x\equiv 1 \mod k$ such that $x\le 2n$.
```

proposed changes:

-  just `$` to open blocks, prices (like `$4.00`) are probably less frequently used and dollar signs can always be \escaped
- `$` to close blocks, to match how latex is written elsewhere
- better clarity on how far my cursor can go before i fall back into the latex block (i frequently dropped in accidentally when trying to add punctuation after a block)

**Comment by wwsalmon** [comment]
probably won't implement "just `$` to open blocks" -- this makes sense for a properly text-based editor like Obsidian (and tbh this is the kind of editor that I prefer, I hope to build one in the future) but not a schema-based one like Postulate. You would never think to escape something in Notion, for example

$ to close is definitely doable though

re: the third point, do you have ideas on how to show this? right now the latex is just in the document flow so spaces are naturally hard to distinguish. I'm guessing this is compounded by the fact that there's a fake "space" within the latex block itself that can't be deleted, so it feels like there are two spaces when only one actually exists. open to suggestions though

**Comment by wwsalmon** [comment]
adding $ to close alone would be a big improvement i think -- typing flow would go `$` `space` `n` `$` and you're on your way

another thing I could add is to try and recognize when `blah blah $latex$` has been typed, then convert `$latex$` to a latex block. this way the initial typing flow would be identical to writing it in a text-based editor

**Comment by DronHazra** [comment]
i agree, binding `$` to close goes most of the way there (i tried using spaces in my regular latex writing and it was mostly fine). i really like the idea of recognizing latex :D would just have to manage what happens if there are multiple prices in a post lol
